
name: Maven Package

on:
  push:
    - branch: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Install prerequisites
      run:
        sudo
        DEBIAN_FRONTEND=noninteractive
        apt-get -y --no-install-recommends install
          siege

    - uses: actions/checkout@v2

    - name: Checkout utils
      uses: actions/checkout@v2
      with:
        repository: CRaC/utils
        path: utils

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-:  

    - run: mvn -B package -s settings.xml -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Test on Vanila JDK
      run: |
        P=$(utils/start-bg.sh \
          -s "Installed features" \
          java -jar target/example-quarkus-1.0-SNAPSHOT-runner.jar)
        curl localhost:8080/hello | grep "hello"
        utils/bench.sh http://localhost:8080/hello
        kill $P

    - name: Download JDK
      run: |
        utils/download-jdk.sh
        sudo tar -axf jdk14-crac.tar.gz

    - name: Prepare warm checkpoint
      run: |
        P=$(utils/start-bg.sh \
        -s "Installed features" \
        -e exitcode \
          jdk14-crac/bin/java \
          -XX:CRaCCheckpointTo=cr \
          -XX:+UnlockDiagnosticVMOptions \
          -XX:+CRTraceStartupTime \
          -Djdk.crac.trace-startup-time=true \
          -jar target/example-quarkus-1.0-SNAPSHOT-runner.jar)

        # warmup the service
        utils/bench.sh http://localhost:8080/hello
        jcmd $P JDK.checkpoint
        [ 137 = $(utils/read-exitcode.sh exitcode) ]

    - name: Test on C/RaC
      run: |
        P=$(utils/start-bg.sh \
          -s "restore-finish" \
          jdk14-crac/bin/java -XX:CRaCRestoreFrom=cr)
        curl localhost:8080/hello | grep "hello"
        utils/bench.sh http://localhost:8080/hello
        kill $P

    - name: Test C/RaC startup time
      run:
        timeout 3 bash -c "jdk14-crac/lib/javatime ; jdk14-crac/bin/java -XX:CRaCRestoreFrom=cr"
        | utils/sel.awk -v from=prestart -v to=restore-finish
