
name: Maven Package

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Install prerequisites
      run:
        sudo
        DEBIAN_FRONTEND=noninteractive
        apt-get -y --no-install-recommends install
          siege

    - uses: actions/checkout@v3

    - name: Checkout utils
      uses: actions/checkout@v3
      with:
        repository: CRaC/utils
        path: utils

    - run: make -C utils

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-:  

    - run: mvn -B package -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Test on Vanila JDK
      run: |
        P=$(utils/start-bg.sh \
          -s "Installed features" \
          java -jar target/quarkus-app/quarkus-run.jar)
        curl localhost:8080/hello | grep "hello"
        utils/bench.sh http://localhost:8080/hello
        kill $P

    - name: Download JDK
      run: |
        archive=$(utils/download-jdk.sh)
        sudo tar -axf $archive
        echo JDK=${archive%%.tar.gz} >> $GITHUB_ENV

    - name: Prepare warm checkpoint
      run: |
        P=$(utils/start-bg.sh \
        -s "Installed features" \
        -e exitcode \
          ${{ env.JDK }}/bin/java \
          -XX:CRaCCheckpointTo=cr \
          -XX:+UnlockDiagnosticVMOptions \
          -XX:+CRTraceStartupTime \
          -Djdk.crac.trace-startup-time=true \
          -jar target/quarkus-app/quarkus-run.jar)

        # warmup the service
        utils/bench.sh http://localhost:8080/hello
        jcmd $P JDK.checkpoint
        [ 137 = $(utils/read-exitcode.sh exitcode) ]

    - name: Test on C/RaC
      run: |
        P=$(utils/start-bg.sh \
          -s "restore-finish" \
          ${{ env.JDK }}/bin/java -XX:CRaCRestoreFrom=cr)
        curl localhost:8080/hello | grep "hello"
        utils/bench.sh http://localhost:8080/hello
        kill $P

    - name: Test C/RaC startup time
      run:
        timeout 3 bash -c "utils/javatime ; ${{ env.JDK }}/bin/java -XX:CRaCRestoreFrom=cr"
        | utils/sel.awk -v from=prestart -v to=restore-finish
